on:
  pull_request:
    branches:
      - main
      - 'design/**'
    paths:
      - 'src/**'
jobs:
  lint:
    name: Lint and generate snapshots
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '18'
          
      - name: Install depencies
        run: yarn install
        
      - name: Build tokens
        run: npm run build:local
        
      - name: Lint code
        run: npm run lint
        
      - name: Test and generate snapshots
        run: npm test -- -u
        
      - name: Checkout PR
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh pr checkout ${{ github.event.pull_request.number }}
      - name: Push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: git push
